# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
