# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_assignment_inputs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='function_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
