# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_assignment_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='inputs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outputs',
            field=models.TextField(),
        ),
    ]
