# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-09 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20180208_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='function_name',
            new_name='function_definition',
        ),
    ]
