# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_assignment_comment_to_code_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='instruction_files/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='instructions_file',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='comment_to_code_ratio',
            field=models.IntegerField(blank=True, default=0, help_text='This number represents the percentage of                     characters that are within comments, compared to the                     entire body of code'),
        ),
    ]
