# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_assignment_instruction_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='instruction_file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='instruction_file',
            field=models.ManyToManyField(blank=True, to='mainapp.InstructionFile'),
        ),
    ]
