# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='inputs',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outputs',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='instructionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='instructionfiles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
