# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20180219_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='inputs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outputs',
            field=models.TextField(),
        ),
    ]
