# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20180219_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.TextField(),
        ),
    ]
