# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author',
            new_name='professor',
        ),
    ]
