# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20180223_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CSC', 'Computer Science'), ('MED', 'Media')], default='CSC', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
