# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20180223_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableCourse',
        ),
    ]
