# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_delete_availablecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
    ]
