# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20180223_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablecourse',
            name='professor',
        ),
        migrations.DeleteModel(
            name='AvailableCourse',
        ),
    ]
