# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='AvailableCourse',
        ),
    ]
