# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_auto_20180227_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_faculty',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a faculty member.', verbose_name='faculty status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a student', verbose_name='student status'),
        ),
    ]
