# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20180304_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_subject',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='section_id',
            new_name='subject',
        ),
    ]
