# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20180304_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_subject',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section_id',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
