# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20180304_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['year', 'season']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('subject', 'number', 'section')]),
        ),
    ]
